// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aaxlqbrmlcwgqjmzvklk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFheGxxYnJtbGN3Z3FqbXp2a2xrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTUzOTMsImV4cCI6MjA2NTU5MTM5M30.nt_EEto29qGA9La94YSWCLvw7IIgUkj0gZYoNI63QwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);